# Generated by Django 4.1.2 on 2022-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='type',
            field=models.CharField(max_length=70),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
